# 📊 Numpy ve Matplotlib

## Numpy

Numpy (Numerical Python) is a core library in Python for numerical calculation. It consists of multidimensional arrays and a rich collection of methods for applying mathematical operations on those arrays.

In [67]:
# Let's look at nested lists

my_list = [1, 2, 5, [0, 1], [2, 3, 5]]

In [68]:
my_list[4][0]

2

### **Why is NumPy Important?**
NumPy is the fundamental library for numerical computation and multi-dimensional data (vector/matrix) operations in Python. It provides speed and efficiency, especially when working with data that is entirely or predominantly numeric.  

**1) Speed and Performance (Why "Fast"?)**
The core data structure of NumPy is the ndarray, which holds a single dtype (homogeneous), such as int32 or float64.
Due to this uniform data type:  
- It is stored more compactly in **memory** (carrying less "extra info/metadata").
- Vectorized operations and linear algebra routines generally run **much faster**.   
Consequently, many libraries (e.g., **scikit-learn**) rely heavily on NumPy arrays for data input because they align perfectly with **linear algebra** and matrix model logic.

**2) NumPy vs. Pandas: When to Use Which?**
- Math / Model Matrices / Large-Scale Numerical Computation: Use NumPy.
- Data Cleaning, Merging, Grouping, and Reporting: Use Pandas.

**3) "Table Features" Present in Pandas but Not in NumPy**
Pandas works more like "Excel":
- **Column names** and **row indices** (e.g., columns like "Age", "Gender"; row labels like "John", "Jack").
- **Join/Merge** (table concatenation).
- **GroupBy** (grouping and summarizing).
- **Time series resampling** (aggregating time series into weekly/monthly buckets).
- **Missing data handling and label alignment** (automatic alignment via index).
- **Heterogeneous tables**: Each column in a DataFrame can have a different dtype.   

NumPy is more "raw" and lower-level:
- It works with **positions** (0, 1, 2...) instead of column/row labels.
- While extremely fast, it lacks the ergonomic "table" capabilities that Pandas offers.

**4) Why is NumPy Like an "Intermediate Step"?**
NumPy is a critical bridge between standard Python lists and Pandas:
- It teaches **vector and matrix logic**.
- It is highly functional for operations like slicing, broadcasting, addition, and multiplication on multi-dimensional data (2D, 3D, etc.).

**5) Appearance: "Raw" and More Technical**
- NumPy arrays often look like nested, regular (symmetric) lists.
- Therefore, they might seem more "intimidating" at first glance compared to Pandas; however, they are incredibly powerful for numerical computation.

## Numpy Arrays
Numpy arrays are great alternatives to Python Lists. Specifically for scientific computing and numerical calculation numpy arrays are much easier to handle and do computation.

How to create a numpy array:

In [69]:
import numpy as np

arr1d = np.array([1, 2, 3])  # Create a one dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # Create two dimensional array

In [70]:
type(arr1d)

numpy.ndarray

In [71]:
print(arr1d.shape)
print(arr2d.shape)

(3,)
(2, 3)


In [72]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

Numpy also provides many functions to create array

In [73]:
# Create an array of all zeros
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [74]:
# Create an array of all ones
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [75]:
# Create a constant array
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [76]:
# Create a 2x2 identity matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [77]:
# Create an array filled with random values
e = np.random.random((2, 2))
print(e)

[[0.81056695 0.72049305]
 [0.72038736 0.70052948]]


### Array indexing
To access any element(s) in a numpy array we use index, something similar to Python lists with a difference that for each dimension of array we will have one index. For example extracting the second value of the first dimension of the arr2d would be: `arr2d[0,2]`.   
For example:   
```python
arr2d[0,2]

In [78]:
a = np.array([[3, 7, 3, 4], [5, 6, 7, 2], [2, 1, 1, 1]])
print(a)

[[3 7 3 4]
 [5 6 7 2]
 [2 1 1 1]]


In [79]:
# Slicing
b = a[:2, 1:3]
print(b)

[[7 3]
 [6 7]]


In [80]:
print(a[0, 1])  # 7

7


In [81]:
b[0, 0] = 3  # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])  # Prints "3"

3


In [82]:
print(b)

[[3 3]
 [6 7]]


In [83]:
print(a)

[[3 3 3 4]
 [5 6 7 2]
 [2 1 1 1]]


There are many useful functions in Numpy. Here we mention some of them.

`append`, `where`, `add`, `random`, `reshape`, `vstack`, `mean`, `median`, `std`, `isnan`,

#### **Exercises (numpy)**

1. Create a 3×3 numpy null array (all the values are zeros)

In [84]:
x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.  Extract all odd numbers from an array

hint: input: `[0,1,2,3,4,5,6,7]` and desired output: `[1,3,5,7]`

In [85]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
y = np.array([])

for i in x:
    if i % 2 != 0:
        y = np.append(y, i)
    else:
        continue

print(y)

[1. 3. 5. 7.]


3. Convert a 1D array to a 2D array with 2 rows
input: `[0,1,2,3,4,5,6,7]`, desired output: `array([[0,1,2,3], [4,5,6,7]])`


In [86]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(x.shape)

y = x.reshape(2, 4)
print(y)


(8,)
[[0 1 2 3]
 [4 5 6 7]]


4.  Get items if they are larger than 5 and smaller than 10, from an array of a.

In [87]:
a = np.arange(0, 15, 2)
b = np.array([])

for x in a:
    if x < 10 and x > 5:
        b = np.append(b, x)

print(b)

[6. 8.]


5. Find the mean, median and standard deviation of `a`.

In [88]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))

7.0
7.0
4.58257569495584


6. What are the indices of a's elements, which are more than 0.5. Define these indices in `a` new variable called `id_x`    
```python
a = np.random.rand(1000)

In [89]:
a = np.random.random(1000)

id_x = np.array([])

for i in range(len(a)):
    if a[i] > 0.5:
        id_x = np.append(id_x, a[i])

print(id_x)
print(len(id_x))

[0.89337467 0.68954766 0.67095639 0.82172585 0.52591882 0.74536238
 0.65233155 0.58240445 0.97171784 0.68196344 0.86122152 0.70741541
 0.85946024 0.95193043 0.92467011 0.89356248 0.72727608 0.86051553
 0.94777868 0.99737866 0.81897147 0.90897135 0.8754573  0.97907713
 0.77287672 0.55584505 0.72455924 0.87554947 0.81274874 0.59293859
 0.6145369  0.99362865 0.89225493 0.95055855 0.77242439 0.98207418
 0.52071848 0.65822132 0.77395895 0.78469872 0.70293127 0.93278007
 0.54792437 0.52523939 0.8296198  0.79006462 0.73402496 0.89057022
 0.57533709 0.51876583 0.6747484  0.97551365 0.72373358 0.66075932
 0.98946835 0.98951216 0.89312162 0.715479   0.55243708 0.81749957
 0.92652438 0.78410251 0.96334194 0.8883288  0.60888186 0.97786234
 0.7582294  0.9915088  0.57774409 0.71130775 0.8278261  0.97334761
 0.65643391 0.84654404 0.92902138 0.87547365 0.80822494 0.82487321
 0.76002442 0.91207543 0.59829369 0.51361928 0.54143589 0.61509868
 0.94276718 0.86276785 0.70337041 0.85439574 0.56820567 0.8226

7. Reverse a vector (first element becomes last).

In [90]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])

x_rev = np.flip(x)
print("First method: ", x_rev)

x_rev2 = x[::-1]
print("Second method:", x_rev2)

First method:  [7 6 5 4 3 2 1 0]
Second method: [7 6 5 4 3 2 1 0]


8. Create random vector of size 10 and insert "0" before the maximum value.

In [91]:
vector = np.random.rand(10)

# Find max numbers index value
max_index = vector.argmax()

vector_rev = np.insert(
    vector, np.argmax(vector), 0
)  # 0 is inserted at the position of maximum number in the array
print(vector_rev)

[0.32134033 0.58629893 0.89942709 0.69789361 0.79006005 0.24030231
 0.64956835 0.8614465  0.46935667 0.         0.99682512]


9. Subtract the mean of each row of a matrix

In [92]:
# 1. Reshape the array into a matrix with two rows and five columns
x = np.reshape(vector, (2, 5))
print("Mean of vector: ", np.mean(vector))

# 2. Print the mean value of each row in the matrix
row_means = np.mean(x, axis=1)
print("Row means:", row_means)

# 3.
row_means_array = np.repeat(row_means, 5).reshape(2, 5)
print("Row means array:\n", row_means_array)

# 4. Subtract the mean value of each row from the corresponding elements in the matrix
x_minus_row_mean = x - row_means_array
print(
    "Matrix with each element subtracted by its corresponding row mean:\n",
    x_minus_row_mean,
)


Mean of vector:  0.6512518941477221
Row means: [0.659004   0.64349979]
Row means array:
 [[0.659004   0.659004   0.659004   0.659004   0.659004  ]
 [0.64349979 0.64349979 0.64349979 0.64349979 0.64349979]]
Matrix with each element subtracted by its corresponding row mean:
 [[-0.33766367 -0.07270507  0.24042309  0.03888961  0.13105605]
 [-0.40319748  0.00606856  0.21794671 -0.17414312  0.35332533]]


How does `repeat` function work?

In [93]:
print(np.repeat(3, 4))
x = np.array([[1, 2], [3, 4]])
print("x matrix:\n", x)
print("Repeat x matrix without axis\n", np.repeat(x, 2))
print("Repeat x matrix 3 times with axis 0\n", np.repeat(x, 3, axis=0))
print("Repeat x matrix 3 times with axis 1\n", np.repeat(x, 3, axis=1))
print("Another repeat exercises:\n", np.repeat(x, [1, 2], axis=0))

[3 3 3 3]
x matrix:
 [[1 2]
 [3 4]]
Repeat x matrix without axis
 [1 1 2 2 3 3 4 4]
Repeat x matrix 3 times with axis 0
 [[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
Repeat x matrix 3 times with axis 1
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
Another repeat exercises:
 [[1 2]
 [3 4]
 [3 4]]


 10. Based on worldometers.info website, the world population on 17th of February 2019 at 11:00 am is ~7684621550 and the average growth rate per day is ~107000.

```ptyhon
# World population
world_pop = 7684621550
# average growth rate per day
growth_rate = 107000
```

Create an array (call it: `world_pop_arr`) which shows the world population from 17th of February until 26th of February. Now create a dictionary with all these information and save the dictionary into a file using `numpy.save`.

In [94]:
world_pop = 7684621550
growth_rate = 107000
days = np.arange(10)

day_of_month = np.arange(17, 27)

future_pop = np.array(world_pop + (growth_rate * days))

# Calculate the population growth rate per day and print it.
daily_population = np.append(day_of_month, future_pop).reshape(2, -1).T
print("Daily World Population:\n", daily_population)

Daily World Population:
 [[        17 7684621550]
 [        18 7684728550]
 [        19 7684835550]
 [        20 7684942550]
 [        21 7685049550]
 [        22 7685156550]
 [        23 7685263550]
 [        24 7685370550]
 [        25 7685477550]
 [        26 7685584550]]
